Update python-package-conda.yml

diff --git a/.github/workflows/python-package-conda.yml b/.github/workflows/python-package-conda.yml
--- a/.github/workflows/python-package-conda.yml
+++ b/.github/workflows/python-package-conda.yml
@@ -28,7 +28,10 @@ jobs:
     - name: Test with python and 38 to fail
       run: |
         export GUESS=38
-        if ! python runme.py
+        if python runme.py
         then
+          echo "Failed"
+          exit 1
+        else
           echo "Guess failed correctly"
         if
