Update python-package-conda.yml

diff --git a/.github/workflows/python-package-conda.yml b/.github/workflows/python-package-conda.yml
--- a/.github/workflows/python-package-conda.yml
+++ b/.github/workflows/python-package-conda.yml
@@ -28,11 +28,6 @@ jobs:
         GUESS: 42
     - name: Test with python and 38 to fail
       run: |
-        if python runme.py; then
-          echo "Failed"
-          exit 1
-        else
-          echo "Guess failed correctly"
-        if
+        python runme.py || (echo "Failed correctly" )
       env:
         GUESS: 38
